### ISSUE TITLE
Support snippet configuration file(s) stored in /usr/...

### ISSUE THREAD

**Issue by evelikov** [rauc/rauc#1252]
**Is your feature request related to a problem? Please describe.**

Currently rauc only supports a configuration file in /etc/rauc/. Which can be problematic if you consider:
 - [stateless systems](https://0pointer.de/blog/projects/stateless.html)
 - systems aiming to preserve end-user changes in /etc, while ensuring rauc isn't broken, upon updates
 - would like to override individual option without having to copy (and potentially process) the whole file

**Describe the solution you'd like**

Would be great if rauc supports the following two:
- support config file(s) in /usr/... as the root configuration place - identically named files in /etc will take precedence allowing for local sysadmin overrides
- support separate snippet handling, allowing fine-grained config control instead of having to copy the whole file only to change a single option

The above two are closely related, although feel free to split/tackle separately if it makes sense.

With the above two in place then distribution/vendor can use `/usr/lib/rauc/00-section-{foo,bar}.conf` as part of their rauc package, with additional standalone overrides via  `/usr/lib/rauc/01-section-foo-change-baz.conf`.

The linked blog post and the `CONFIGURATION DIRECTORIES AND PRECEDENCE` section of `man sysctl.d` (among others) provides good additional details on the Whys and Hows.

Thanks in advance

**Comment by jluebbe** [comment]
Are you aware of an implementation for GKeyFile which already handles this? It seems a bit wasteful to reimplement this in each application. :)

**Comment by jluebbe** [comment]
I've been wondering about why this has not come up before and I think it's because the `system.conf` is describes aspects of the system which are very static (as it was designed to do ;). One aspect that is a bit more dynamic is the set of trusted certificates and this supports drop-ins via `[keyring]`/`directory=foo` (just a single directory, though).

This means that the case for changing parts of the `system.conf` on a specific system doesn't come up in most RAUC deployments. Which end-user changes to the `system.conf` are you thinking about?

So, given that there is no support for merging drop-ins in `GKeyFile` and the need for it doesn't seem to be widespread, I wouldn't want to implement/maintain it in RAUC itself. If there was support for that in glib though, it would be a completely different situation. :)

What I'd find useful (even without drop-ins) would be a search order for the `system.conf`, following the common precedence of `/etc` over `/run` over `/usr/lib`. That should already solve some aspects of stateless systems without increased complexity in RAUC.

**Comment by Bastian-Krause** [comment]
Note: We had a similar discussion and a draft PR using libeconf in https://github.com/rauc/rauc-hawkbit-updater/pull/84.

**Comment by jluebbe** [comment]
As a summary, we think that a search order for the `system.conf`, following the common precedence of `/etc` over `/run` over `/usr/lib`, would be a good enhancement for RAUC.

**Comment by a3f** [comment]
Now that I am reading the issue title again, I see that PR #1557 only addressed the prerequisite support for hermetic-usr. Snippet support is yet unimplemented. I think we should reopen the issue, or what do you think, @evelikov?

**Comment by ejoerns** [comment]
I checked before merging if the PR should actually close this issue and concluded that since the previous comments have spoken out against implementing the snippet part in RAUC itself (and glib won't soon), closing it would be fine for now.
For those interested, the issue would however still be searchable and could be re-opened later. But I am open to other and recent opinions on this topic.

**Comment by evelikov** [comment]
The key part - supporting `/etc` and `/run` - is tackled so it's fine to close. The fragment support is a nice-to-have and would make sense to introduce _if_ there is a big demand for it IMHO.
