### ISSUE TITLE
failed to load kernel modules after a+b update 

### ISSUE THREAD

**Issue by ghost** [rauc/rauc#1315]
**Describe the bug**
Performed an a+b rootfs update and rauc successfully installed the bundle.
After rebooting the board the the bootloader booted from the new slot.
But when the kernel booted; it could not find the kernel modules.
Inspecting the kernel revision id; we see the correct kernel revision id with the commit id
Inspecting the /lib/modules directory; we see the correct revision id but the commit is different.

From the above; why did rauc not update the commit if of the kernel?
Also is rauc performed a comlete update or partial?

**Comment by ejoerns** [comment]
@pritpalm-kuk RAUC replaces full (file system) images. If I understood it correctly, kernel and modules are all part of the rootfs?
Thus if there is an inconsistency, this must be produced by your Embedded Linux build system, not by RAUC.

**Comment by pritpalm-kuk** [comment]
ejoerns the kernel and modules are a part of the rootfs.
what we dont seem to understand is when we use the command uname -r we get the kernel revision; but the commit id is different to the directory in /lib/modules

**Comment by ejoerns** [comment]
@pritpalm-kuk you should be able to check if this is already the case for the image image contained in your bundle.
If you do not have it anymore, use `unsquashfs` or `rauc extract` to extract the bundle content.
RAUC does not modify the image contents.

Since I have no insight into your rootfs creation, it is quite hard for me to help you to debug this.
