### ISSUE TITLE
Handler/Hook after all slots are successfully updated

### ISSUE THREAD

**Issue by embeddedrocks** [rauc/rauc#275]
Hi,

I'm using your updater since a while now and are very pleased with it. Please continue the great work.

I just came across an issue which is either not implemented or I just overlooked it.

The idea is to either have a handler or hook after all slots have been successfully updated. 
You offer a post-install handler within the system.conf file. Which is indeed executed after an update has been successfully installed. But it is still executed from the *old* system. So my *old* system need to know about things I would like to do in the future.
The slot hooks won't work either as I need to be sure all slots have been updated. Which is not the case if e.g. I use a hook in _appfs_ slot but don't know if _rootfs_ has already been updated.

The plan is to copy some files from the *new* _appfs_ into the *new* _rootfs_. Unfortunately I have to do it this way as I cannot modify the _rootfs_ during build time.

Many Thanks.

**Comment by ejoerns** [comment]
Maybe this is something that should be handled in the newly booting system instead of during updating?

If you are using systemd, you might want to have a look at

https://www.freedesktop.org/software/systemd/man/systemd.offline-updates.html

or 

https://www.freedesktop.org/software/systemd/man/systemd-firstboot.html

Would that help in your case?

**Comment by embeddedrocks** [comment]
Many thanks for your answer.

Unfortunately it doesn't suite my case, as it assumes a modifyable _rootfs_ system during build time. Otherwise I'm not able to add a systemd services, which could be done during the update by copying files to the _new rootfs_ and further execute _systemctl_ with the _--root_ option. 

When using the slot hook mechanism, is there a chance to validate that e.g. _slot A_ is already updated when _slot B_ is executed. Or in other words, are slots always updated in a fixed order?

**Comment by ejoerns** [comment]
If I get it right, you have a system where one has control over the appfs image but not over the rootfs image, right?
Maybe one could prepare the rootfs to have a mechanism to copy the required data from its appfs when being booted and create the trigger not in the rootfs itself but in a rootfs post-install hook. This one could add for example the mentioned `system-install` symlink without the need to actually touch the rootfs image itself.

> When using the slot hook mechanism, is there a chance to validate that e.g. slot A is already updated when slot B is executed. Or in other words, are slots always updated in a fixed order?

Up to now, there is no guarantee about that. It will have a fixed order ATM, but this is only defined by the code and the way it uses the data containers. It might change if another handling is implemented thus it is unsafe ATM to rely on a specific order.
There might be usecases for forcing a specifc order, e.g. when doing bootloader updates and having a non-redundant one. Then we might want to ensure the bootloader is updated as the very last slot. Because, if we updated it already and then for example the rootsf update fails, we have a new bootloader but only the old rootfs where booting with the new loader is not that good tested for.

> An additional question: Is it possible to access slot A within the post-install hook when currently updationg slot B?

Potentially yes, you can do everything a script can do and you know about the different devices handeld by RAUC during hook execution, but this will not give any guarantee that the content of A isn't overwritten when it is updated after B (see above).

The only safe place to do such things would be in the post-install handler as this assures all slot updates are completed. But I am not sure if there is any benefit over the solution I mentioned at the top, as both require to modify the rootfs.

Maybe this also reveals that there is also a need for a post-install *hook*!?

**Comment by embeddedrocks** [comment]
Indeed you are right with your assumption. I'm able to modify the _appfs_ but not the _rootfs_.
Your mentioned idea is essentially the way I will proceed. I will write service files to _rootfs_ within the `post-install hook`. These services will be enabled via `systemctl --root`.
This should cover my current problem.

But in regards to your question:
> Maybe this also reveals that there is also a need for a post-install hook!?

I would acknowledge that and it would be a good feature in a future version.

Many thanks for your help, ideas and comments! I think this can be closed.

**Comment by ejoerns** [comment]
I kept this open having the need for the post-install hook visible.

With #342 this is now obsolete and we can safely close this thread.
