### ISSUE TITLE
attach file to bundle

### ISSUE THREAD

**Issue by ilkondr** [rauc/rauc#333]
Hi folks,
I'm trying to get configured pre-install and post-install hooks, which are not slot-related, but system-related. So I would like to have code put into bundle with behaviour of **handlers**. Is there any internal solution for this? Is there way to just attach a file to bundle?

In order to attach file I tried to add new slot with type=file to manifest (tarball with my scripts).
Than I created handlers which unpack tarball and execute scripts. Sounds good.
But rauc install does not work for me if manifest has extra slot (system.conf with 3 slots and bundle manifest with 4 slots).
As you can see install succeeded but no update performed:

```
rauc[282]: Starting pre install handler: /etc/rauc/pre-install.sh
rauc[282]: Using default handler
rauc[282]: (rauc:282): rauc-WARNING **: No target slot for class upgrade-handlers of image upgrade-handlers.tar.img found
rauc[282]: rauc-Message: Marking target slot as non-bootable...
rauc[282]: rauc-Message: Marking slots as bootable...
rauc[282]: rauc-Message: installing /home/root/bundle.raucb: Updating slots...
rauc[282]: rauc-Message: installing /home/root/bundle.raucb: All slots updated
rauc[282]: Starting post install handler: /etc/rauc/post-install.sh
rauc[282]: rauc-Message: installing /home/root/bundle.raucb: finished
rauc[282]: rauc-Message: installing `/home/root/bundle.raucb` succeeded
```

That would be great if there is a way to get things working with extra slot.
Thanks

**Comment by ejoerns** [comment]
Hi @ilkondr 

Several things on this:

* An image listed in the manifest must have a corresponding slot (class) listed in system.conf. This is what your log already rejected and what is by intention

* Attaching a file to a bundle is quite easy, RAUC packs all files that are located in the folder you create your bundle from together. There is no need to list it in the manifest.

* Hooks lack support for pre- and post-install. This is not intentionally but simply because it is not implemented yet -> patches welcome

Thus, without adding support to the handlers, the only way to achieve what you described would be to use a handler and simply put the image into the bundle. Build system integration for this might be missing -> patches welcome :)

Anyway, to better understand what would fit your needs, could you explain what actual purpose of your extra image / archive is? It means, what do you want to do with it? Bootstrapping something? Adding additional content to a slot? ..

**Comment by ejoerns** [comment]
@ilkondr Thanks for proposing a solution for adding extra files in meta-rauc! I link it here for reference: https://github.com/rauc/meta-rauc/pull/53

You are also right that your case should be fatal but unintentionally it became a warning only. In master, this is already fixed by https://github.com/rauc/rauc/commit/3f4953bd27729c2af216061b8a3c3d639ba2d00d

**Comment by ejoerns** [comment]
Yocto support was added with https://github.com/rauc/meta-rauc/pull/102
