### ISSUE TITLE
Release filename vs. tag name mismatch for release candidates

### ISSUE THREAD

**Issue by mhei** [rauc/rauc#357]
Not a major problem, but not nice in my eyes:

The filename of the released tarball has a dot before "rc1", but the tag name contains a hyphen:
https://github.com/rauc/rauc/releases/download/v1.0-rc1/rauc-1.0.rc1.tar.xz

This prevents me from using something like this:

```
# helper variable
rauc_version=1.0.rc1

# download
wget https://github.com/rauc/rauc/releases/download/v${rauc_version}/rauc-${rauc_version}.tar.xz

```

Usual releases will probably not be affected due to missing hyphen, but maybe we can fix it.

**Comment by ejoerns** [comment]
If I remember correctly what @jluebbe said, the git-version-gen script failed to handle the 1.0-rc1 name because of the hyphen. This made us use the dot as a 'workaround'.

As you said, fortunately we will not run into this issue when doing the 1.0 release and it is still unclear if we continue doing release candidates as we did for 1.0 now to not break anything on such a remarkable release tag ;) (Despite the most of the important functionality is backed by testing, anyway)
