### ISSUE TITLE
Installing update on a device with expired certificate

### ISSUE THREAD

**Issue by jkryszyn** [rauc/rauc#781]
Hello,
I am using rauc 1.1. When I do `rauc install update.raucb` on my device, I get the following output:

```
rauc-Message: 07:30:31.315: installing update.raucb: installing
rauc-Message: 07:30:31.334: installing update.raucb:   0% Installing
rauc-Message: 07:30:31.337: installing update.raucb:   0% Determining slot states
rauc-Message: 07:30:31.347: installing update.raucb:  20% Determining slot states done.
rauc-Message: 07:30:31.357: installing update.raucb:  20% Checking bundle
rauc-Message: 07:30:31.368: installing update.raucb:  20% Verifying signature
rauc-Message: 07:30:31.376: installing update.raucb:  40% Verifying signature failed.
rauc-Message: 07:30:31.397: installing update.raucb:  40% Checking bundle failed.
rauc-Message: 07:30:31.410: installing update.raucb: 100% Installing failed.
rauc-Message: 07:30:31.416: installing update.raucb: LastError: signature verification failed: Verify error:certificate has expired
```

The certificate on the device is outdated. Is there any chance to force the update (for example by producing my bundle in some special way) or do I have to exchange this certificate file on the device?

**Comment by ejoerns** [comment]
Hi @jkryszyn,
no, you will not be able to update the device anymore without manually modifying it.

Using the bundle signing time instead of the system time for verification is theoretically possible with the `system.conf` option `use-bundle-signing-time=true`, but that would require manual interaction too. Thus I would propose to replace the certificate and choose the lifetime wisely for your next one.

Also, note that not only the certificate is outdated, but the RAUC version is also. I highly recommend updating to 1.5.1, for example because of https://nvd.nist.gov/vuln/detail/CVE-2020-25860.

**Comment by jluebbe** [comment]
This works as intended, so there's nothing we can do on RAUC's side.
